# Generated by Django 2.1.1 on 2018-09-03 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('point_of_contact_name', models.CharField(max_length=100)),
                ('point_of_contact_number', models.PositiveIntegerField()),
                ('point_of_contact_email', models.EmailField(max_length=100)),
                ('source_of_job', models.CharField(max_length=255)),
                ('link_to_job_posting', models.URLField()),
                ('notes', models.TextField(blank=True)),
                ('timeline', multiselectfield.db.fields.MultiSelectField(choices=[('Submitted Job Application', 'Submitted Job Application'), ('Whiteboarding', 'Whiteboarding'), ('Code Test', 'Code Test'), ('On-Site Interview', 'On-Site Interview'), ('Received Response', 'Received Response'), ('Phone Interview', 'Phone Interview')], max_length=101)),
                ('heart_it', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Application',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('application.application',),
        ),
    ]
