# Generated by Django 2.1.1 on 2018-09-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='link_to_job_posting',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='point_of_contact_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='point_of_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='point_of_contact_number',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='source_of_job',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
