# Generated by Django 2.1.1 on 2018-09-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20180903_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='timeline',
        ),
    ]
